server:
   port:8081

app:
 feign:
   config: 
      name:instantwebtools-api
      url:https://api.instantwebtools.net/v1/


feign:
  client:
    config:
       default:
          connect-timeout:20000
          read-timeout:20000