server:
port: 9090
spring:
datasource:
driverClassName: org.postgresql.Driver
password: Sumitraj
url: jdbc:postgresql://localhost:5432/RESTPOC4
username: postgres
jpa:
database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
ddl-auto: update


